# Change column names for better reproducibility

In [21]:
import pandas as pd


df = pd.read_csv('dataset/yelp_review_polarity_dataset/yelp_polarity_train.csv')

df.head(10)

,1,"Unfortunately, the frustration of being Dr. Goldberg's patient is a repeat of the experience I've had with so many other doctors in NYC -- good doctor, terrible staff. It seems that his staff simply never answers the phone. It usually takes 2 hours of repeated calling to get an answer. Who has time for that or wants to deal with it? I have run into this problem with many other doctors and I just don't get it. You have office workers, you have patients with medical needs, why isn't anyone answering the phone? It's incomprehensible and not work the aggravation. It's with regret that I feel that I have to give Dr. Goldberg 2 stars."
0,2,Been going to Dr. Goldberg for over 10 years. ...
1,1,I don't know what Dr. Goldberg was like before...
2,1,I'm writing this review to give you a heads up...
3,2,All the food is great here. But the best thing...
4,1,Wing sauce is like water. Pretty much a lot of...
5,1,Owning a driving range inside the city limits ...
6,1,This place is absolute garbage... Half of the...
7,2,Before I finally made it over to this range I ...
8,2,I drove by yesterday to get a sneak peak. It ...
9,1,After waiting for almost 30 minutes to trade i...

In [22]:
# Change the column names
old_name1 = df.columns[0]
df.rename(columns={old_name1: 'sentiment'}, inplace=True)

old_name = df.columns[1]

df.rename(columns={old_name: 'text'}, inplace=True)

df.head(10)

   sentiment                                               text
0          2  Been going to Dr. Goldberg for over 10 years. ...
1          1  I don't know what Dr. Goldberg was like before...
2          1  I'm writing this review to give you a heads up...
3          2  All the food is great here. But the best thing...
4          1  Wing sauce is like water. Pretty much a lot of...
5          1  Owning a driving range inside the city limits ...
6          1  This place is absolute garbage...  Half of the...
7          2  Before I finally made it over to this range I ...
8          2  I drove by yesterday to get a sneak peak.  It ...
9          1  After waiting for almost 30 minutes to trade i...

In [23]:
# Convert the sentiment column to 'positive' and 'negative'
df['sentiment'] = df['sentiment'].map({1: 'negative', 2: 'positive'})

In [24]:
df.to_csv('dataset/yelp_review_polarity_dataset/updated_yelp_polarity_train.csv', index=False)

# Making the Tweet dataset uniform (similar col values to yelp dataset)