# Change column names for better reproducibility

In [11]:
import pandas as pd


df = pd.read_csv('dataset/yelp_review_polarity_dataset/yelp_polarity_test.csv')

df.head(10)

,2,"Contrary to other reviews, I have zero complaints about the service or the prices. I have been getting tire service here for the past 5 years now, and compared to my experience with places like Pep Boys, these guys are experienced and know what they're doing. \nAlso, this is one place that I do not feel like I am being taken advantage of, just because of my gender. Other auto mechanics have been notorious for capitalizing on my ignorance of cars, and have sucked my bank account dry. But here, my service and road coverage has all been well explained - and let up to me to decide. \nAnd they just renovated the waiting room. It looks a lot better than it did in previous years."
0,1,Last summer I had an appointment to get new ti...
1,2,"Friendly staff, same starbucks fair you get an..."
2,1,The food is good. Unfortunately the service is...
3,2,Even when we didn't have a car Filene's Baseme...
4,2,"Picture Billy Joel's \""Piano Man\"" DOUBLED mix..."
5,1,Mediocre service. COLD food! Our food waited s...
6,1,Ok! Let me tell you about my bad experience fi...
7,1,I used to love D&B when it first opened in the...
8,2,"Like any Barnes & Noble, it has a nice comfy c..."
9,1,"Meh, I've experienced better is an understatem..."

In [12]:
# Change the column names
df.rename(columns={'2': 'sentiment'}, inplace=True)

old_name = df.columns[1]

df.rename(columns={old_name: 'text'}, inplace=True)

df.head(10)

   sentiment                                               text
0          1  Last summer I had an appointment to get new ti...
1          2  Friendly staff, same starbucks fair you get an...
2          1  The food is good. Unfortunately the service is...
3          2  Even when we didn't have a car Filene's Baseme...
4          2  Picture Billy Joel's \"Piano Man\" DOUBLED mix...
5          1  Mediocre service. COLD food! Our food waited s...
6          1  Ok! Let me tell you about my bad experience fi...
7          1  I used to love D&B when it first opened in the...
8          2  Like any Barnes & Noble, it has a nice comfy c...
9          1  Meh, I've experienced better is an understatem...

In [13]:
df.to_csv('dataset/yelp_review_polarity_dataset/updated_yelp_polarity_test.csv', index=False)