In [1]:
# Reference: https://www.kaggle.com/snap/amazon-fine-food-reviews
# Reference: https://www.youtube.com/watch?v=QpzMWQvxXWk&t=204s&ab_channel=RobMulla
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

import nltk 
from nltk import download
download('punkt')
download('averaged_perceptron_tagger')
download('maxent_ne_chunker')
download('words')

# Read in the data
df = pd.read_csv('../dataset/amazon_fine_food_reviews/amazon_reviews.csv')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/thomashazekamp/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/thomashazekamp/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /Users/thomashazekamp/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to
[nltk_data]     /Users/thomashazekamp/nltk_data...
[nltk_data]   Package words is already up-to-date!

In [2]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [3]:
df = df.head(500) # Only top 500 reviews - for testing purposes

In [4]:
example = df['Text'][50]
print(example)

This oatmeal is not good. Its mushy, soft, I don't like it. Quaker Oats is the way to go.

In [5]:
tokens = nltk.word_tokenize(example)

nltk_pos_tagged = nltk.pos_tag(tokens) # Part of speech tagging - gives each token a tag (e.g. noun, verb, etc.)

In [6]:
entities = nltk.chunk.ne_chunk(nltk_pos_tagged) # Named entity recognition - identifies named entities (e.g. person, place, etc.)
entities.pprint()

(S
  This/DT
  oatmeal/NN
  is/VBZ
  not/RB
  good/JJ
  ./.
  Its/PRP$
  mushy/NN
  ,/,
  soft/JJ
  ,/,
  I/PRP
  do/VBP
  n't/RB
  like/VB
  it/PRP
  ./.
  (ORGANIZATION Quaker/NNP Oats/NNPS)
  is/VBZ
  the/DT
  way/NN
  to/TO
  go/VB
  ./.)

In [7]:
## Using Vader to perform sentiment analysis
# - Vader does not account the relationship between words in a sentence, so it is not as accurate as other methods

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

sia.polarity_scores(example) # Using Vader to perform sentiment analysis on the example review, showing negative, neutral, positive, and compound scores (-1 to 1 on how negative/positive the review is)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/thomashazekamp/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

{'neg': 0.22, 'neu': 0.78, 'pos': 0.0, 'compound': -0.5448}

In [9]:
# Find polarity scores for all reviews
res = {}
for i, row in tqdm(df.iterrows()):
    text = row['Text']
    myid = row['Id']
    res[myid] = sia.polarity_scores(text)

res # Show the dictionary of the polarity scores for each review

0it [00:00, ?it/s]

{1: {'neg': 0.0, 'neu': 0.695, 'pos': 0.305, 'compound': 0.9441},
 2: {'neg': 0.138, 'neu': 0.862, 'pos': 0.0, 'compound': -0.5664},
 3: {'neg': 0.091, 'neu': 0.754, 'pos': 0.155, 'compound': 0.8265},
 4: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 5: {'neg': 0.0, 'neu': 0.552, 'pos': 0.448, 'compound': 0.9468},
 6: {'neg': 0.029, 'neu': 0.809, 'pos': 0.163, 'compound': 0.883},
 7: {'neg': 0.034, 'neu': 0.693, 'pos': 0.273, 'compound': 0.9346},
 8: {'neg': 0.0, 'neu': 0.52, 'pos': 0.48, 'compound': 0.9487},
 9: {'neg': 0.0, 'neu': 0.851, 'pos': 0.149, 'compound': 0.6369},
 10: {'neg': 0.0, 'neu': 0.705, 'pos': 0.295, 'compound': 0.8313},
 11: {'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'compound': 0.9746},
 12: {'neg': 0.113, 'neu': 0.887, 'pos': 0.0, 'compound': -0.7579},
 13: {'neg': 0.031, 'neu': 0.923, 'pos': 0.046, 'compound': 0.296},
 14: {'neg': 0.0, 'neu': 0.355, 'pos': 0.645, 'compound': 0.9466},
 15: {'neg': 0.104, 'neu': 0.632, 'pos': 0.264, 'compound': 0.6486},
 16: {'neg': 0.0, 'neu': 0.861, 'pos': 0.139, 'compound': 0.5719},
 17: {'neg': 0.097, 'neu': 0.694, 'pos': 0.209, 'compound': 0.7481},
 18: {'neg': 0.0, 'neu': 0.61, 'pos': 0.39, 'compound': 0.8883},
 19: {'neg': 0.012, 'neu': 0.885, 'pos': 0.103, 'compound': 0.8957},
 20: {'neg': 0.0, 'neu': 0.863, 'pos': 0.137, 'compound': 0.6077},
 21: {'neg': 0.0, 'neu': 0.865, 'pos': 0.135, 'compound': 0.6249},
 22: {'neg': 0.0, 'neu': 0.739, 'pos': 0.261, 'compound': 0.9153},
 23: {'neg': 0.0, 'neu': 0.768, 'pos': 0.232, 'compound': 0.7687},
 24: {'neg': 0.085, 'neu': 0.771, 'pos': 0.143, 'compound': 0.2617},
 25: {'neg': 0.038, 'neu': 0.895, 'pos': 0.068, 'compound': 0.3939},
 26: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 27: {'neg': 0.128, 'neu': 0.872, 'pos': 0.0, 'compound': -0.296},
 28: {'neg': 0.04, 'neu': 0.808, 'pos': 0.152, 'compound': 0.5956},
 29: {'neg': 0.022, 'neu': 0.669, 'pos': 0.309, 'compound': 0.9913},
 30: {'neg': 0.017, 'neu': 0.846, 'pos': 0.137, 'compound': 0.9746},
 31: {'neg': 0.041, 'neu': 0.692, 'pos': 0.267, 'compound': 0.9713},
 32: {'neg': 0.0, 'neu': 0.484, 'pos': 0.516, 'compound': 0.9153},
 33: {'neg': 0.069, 'neu': 0.839, 'pos': 0.092, 'compound': 0.7103},
 34: {'neg': 0.024, 'neu': 0.72, 'pos': 0.256, 'compound': 0.9779},
 35: {'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'compound': 0.9091},
 36: {'neg': 0.024, 'neu': 0.821, 'pos': 0.155, 'compound': 0.7622},
 37: {'neg': 0.0, 'neu': 0.754, 'pos': 0.246, 'compound': 0.9196},
 38: {'neg': 0.0, 'neu': 0.938, 'pos': 0.062, 'compound': 0.4457},
 39: {'neg': 0.05, 'neu': 0.846, 'pos': 0.104, 'compound': 0.7638},
 40: {'neg': 0.0, 'neu': 0.856, 'pos': 0.144, 'compound': 0.8114},
 41: {'neg': 0.033, 'neu': 0.82, 'pos': 0.147, 'compound': 0.9301},
 42: {'neg': 0.03, 'neu': 0.848, 'pos': 0.122, 'compound': 0.9435},
 43: {'neg': 0.0, 'neu': 0.588, 'pos': 0.412, 'compound': 0.9441},
 44: {'neg': 0.0, 'neu': 0.685, 'pos': 0.315, 'compound': 0.9161},
 45: {'neg': 0.031, 'neu': 0.778, 'pos': 0.191, 'compound': 0.8421},
 46: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 47: {'neg': 0.0, 'neu': 0.737, 'pos': 0.263, 'compound': 0.9169},
 48: {'neg': 0.0, 'neu': 0.868, 'pos': 0.132, 'compound': 0.4404},
 49: {'neg': 0.0, 'neu': 0.821, 'pos': 0.179, 'compound': 0.747},
 50: {'neg': 0.056, 'neu': 0.865, 'pos': 0.079, 'compound': 0.2363},
 51: {'neg': 0.22, 'neu': 0.78, 'pos': 0.0, 'compound': -0.5448},
 52: {'neg': 0.047, 'neu': 0.735, 'pos': 0.218, 'compound': 0.9194},
 53: {'neg': 0.09, 'neu': 0.858, 'pos': 0.052, 'compound': -0.8259},
 54: {'neg': 0.075, 'neu': 0.925, 'pos': 0.0, 'compound': -0.3612},
 55: {'neg': 0.0, 'neu': 0.857, 'pos': 0.143, 'compound': 0.8761},
 56: {'neg': 0.071, 'neu': 0.708, 'pos': 0.221, 'compound': 0.8908},
 57: {'neg': 0.029, 'neu': 0.694, 'pos': 0.277, 'compound': 0.908},
 58: {'neg': 0.0, 'neu': 0.701, 'pos': 0.299, 'compound': 0.91},
 59: {'neg': 0.0, 'neu': 0.611, 'pos': 0.389, 'compound': 0.9323},
 60: {'neg': 0.0, 'neu': 0.638, 'pos': 0.362, 'compound': 0.8807},
 61: {'neg': 0.0, 'neu': 0.9, 'pos': 0.1, 'compound': 0.4404},
 62: {'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'compound': 0.8442},
 63: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 64: {'neg': 0.055, 'neu': 0.765, 'pos': 0.179, 'compound': 0.9817},
 65: {'neg': 0.046, 'neu': 0.75, 'pos': 0.205, 'compound': 0.8674},
 66: {'neg': 0.04, 'neu': 0.822, 'pos': 0.138, 'compound': 0.5165},
 67: {'neg': 0.057, 'neu': 0.869, 'pos': 0.073, 'compound': 0.492},
 68: {'neg': 0.183, 'neu': 0.776, 'pos': 0.041, 'compound': -0.9116},
 69: {'neg': 0.135, 'neu': 0.71, 'pos': 0.155, 'compound': -0.0096},
 70: {'neg': 0.344, 'neu': 0.52, 'pos': 0.136, 'compound': -0.7345},
 71: {'neg': 0.036, 'neu': 0.916, 'pos': 0.048, 'compound': 0.2228},
 72: {'neg': 0.078, 'neu': 0.701, 'pos': 0.222, 'compound': 0.9733},
 73: {'neg': 0.025, 'neu': 0.653, 'pos': 0.323, 'compound': 0.9787},
 74: {'neg': 0.093, 'neu': 0.762, 'pos': 0.144, 'compound': 0.9665},
 75: {'neg': 0.0, 'neu': 0.872, 'pos': 0.128, 'compound': 0.2263},
 76: {'neg': 0.106, 'neu': 0.768, 'pos': 0.126, 'compound': 0.1098},
 77: {'neg': 0.019, 'neu': 0.898, 'pos': 0.083, 'compound': 0.5647},
 78: {'neg': 0.034, 'neu': 0.798, 'pos': 0.168, 'compound': 0.8303},
 79: {'neg': 0.0, 'neu': 0.763, 'pos': 0.237, 'compound': 0.7814},
 80: {'neg': 0.087, 'neu': 0.589, 'pos': 0.324, 'compound': 0.8636},
 81: {'neg': 0.0, 'neu': 0.723, 'pos': 0.277, 'compound': 0.9098},
 82: {'neg': 0.0, 'neu': 0.663, 'pos': 0.337, 'compound': 0.9041},
 83: {'neg': 0.04, 'neu': 0.794, 'pos': 0.165, 'compound': 0.9957},
 84: {'neg': 0.055, 'neu': 0.767, 'pos': 0.178, 'compound': 0.8642},
 85: {'neg': 0.109, 'neu': 0.676, 'pos': 0.214, 'compound': 0.8431},
 86: {'neg': 0.035, 'neu': 0.698, 'pos': 0.267, 'compound': 0.9487},
 87: {'neg': 0.019, 'neu': 0.855, 'pos': 0.126, 'compound': 0.8797},
 88: {'neg': 0.05, 'neu': 0.735, 'pos': 0.215, 'compound': 0.7424},
 89: {'neg': 0.048, 'neu': 0.762, 'pos': 0.19, 'compound': 0.9716},
 90: {'neg': 0.029, 'neu': 0.645, 'pos': 0.326, 'compound': 0.9554},
 91: {'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'compound': 0.7351},
 92: {'neg': 0.0, 'neu': 0.837, 'pos': 0.163, 'compound': 0.6249},
 93: {'neg': 0.069, 'neu': 0.663, 'pos': 0.268, 'compound': 0.8255},
 94: {'neg': 0.01, 'neu': 0.781, 'pos': 0.208, 'compound': 0.9882},
 95: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 96: {'neg': 0.031, 'neu': 0.732, 'pos': 0.237, 'compound': 0.9273},
 97: {'neg': 0.0, 'neu': 0.818, 'pos': 0.182, 'compound': 0.982},
 98: {'neg': 0.053, 'neu': 0.793, 'pos': 0.154, 'compound': 0.7729},
 99: {'neg': 0.024, 'neu': 0.91, 'pos': 0.066, 'compound': 0.5106},
 100: {'neg': 0.173, 'neu': 0.735, 'pos': 0.092, 'compound': -0.5267},
 101: {'neg': 0.0, 'neu': 0.807, 'pos': 0.193, 'compound': 0.7717},
 102: {'neg': 0.103, 'neu': 0.752, 'pos': 0.145, 'compound': 0.2285},
 103: {'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.9287},
 104: {'neg': 0.0, 'neu': 0.859, 'pos': 0.141, 'compound': 0.7249},
 105: {'neg': 0.051, 'neu': 0.577, 'pos': 0.372, 'compound': 0.9313},
 106: {'neg': 0.0, 'neu': 0.696, 'pos': 0.304, 'compound': 0.9603},
 107: {'neg': 0.0, 'neu': 0.791, 'pos': 0.209, 'compound': 0.5719},
 108: {'neg': 0.0, 'neu': 0.804, 'pos': 0.196, 'compound': 0.9503},
 109: {'neg': 0.059, 'neu': 0.676, 'pos': 0.265, 'compound': 0.9116},
 110: {'neg': 0.014, 'neu': 0.764, 'pos': 0.222, 'compound': 0.9841},
 111: {'neg': 0.059, 'neu': 0.879, 'pos': 0.062, 'compound': 0.0176},
 112: {'neg': 0.0, 'neu': 0.81, 'pos': 0.19, 'compound': 0.8769},
 113: {'neg': 0.037, 'neu': 0.786, 'pos': 0.177, 'compound': 0.9946},
 114: {'neg': 0.0, 'neu': 0.631, 'pos': 0.369, 'compound': 0.8779},
 115: {'neg': 0.027, 'neu': 0.727, 'pos': 0.245, 'compound': 0.9379},
 116: {'neg': 0.0, 'neu': 0.645, 'pos': 0.355, 'compound': 0.872},
 117: {'neg': 0.0, 'neu': 0.892, 'pos': 0.108, 'compound': 0.6573},
 118: {'neg': 0.0, 'neu': 0.781, 'pos': 0.219, 'compound': 0.9751},
 119: {'neg': 0.05, 'neu': 0.872, 'pos': 0.079, 'compound': 0.8972},
 120: {'neg': 0.013, 'neu': 0.785, 'pos': 0.203, 'compound': 0.9828},
 121: {'neg': 0.026, 'neu': 0.759, 'pos': 0.215, 'compound': 0.9509},
 122: {'neg': 0.102, 'neu': 0.822, 'pos': 0.076, 'compound': -0.3626},
 123: {'neg': 0.025, 'neu': 0.803, 'pos': 0.172, 'compound': 0.9022},
 124: {'neg': 0.017, 'neu': 0.795, 'pos': 0.188, 'compound': 0.9769},
 125: {'neg': 0.079, 'neu': 0.67, 'pos': 0.252, 'compound': 0.9678},
 126: {'neg': 0.035, 'neu': 0.87, 'pos': 0.095, 'compound': 0.5709},
 127: {'neg': 0.0, 'neu': 0.721, 'pos': 0.279, 'compound': 0.9258},
 128: {'neg': 0.067, 'neu': 0.633, 'pos': 0.299, 'compound': 0.9022},
 129: {'neg': 0.043, 'neu': 0.728, 'pos': 0.229, 'compound': 0.8142},
 130: {'neg': 0.114, 'neu': 0.676, 'pos': 0.21, 'compound': 0.6721},
 131: {'neg': 0.0, 'neu': 0.755, 'pos': 0.245, 'compound': 0.8658},
 132: {'neg': 0.135, 'neu': 0.76, 'pos': 0.105, 'compound': -0.3612},
 133: {'neg': 0.046, 'neu': 0.772, 'pos': 0.181, 'compound': 0.7902},
 134: {'neg': 0.02, 'neu': 0.878, 'pos': 0.103, 'compound': 0.8082},
 135: {'neg': 0.0, 'neu': 0.877, 'pos': 0.123, 'compound': 0.4215},
 136: {'neg': 0.0, 'neu': 0.9, 'pos': 0.1, 'compound': 0.6503},
 137: {'neg': 0.0, 'neu': 0.695, 'pos': 0.305, 'compound': 0.9661},
 138: {'neg': 0.0, 'neu': 0.689, 'pos': 0.311, 'compound': 0.8591},
 139: {'neg': 0.15, 'neu': 0.773, 'pos': 0.077, 'compound': -0.4199},
 140: {'neg': 0.043, 'neu': 0.833, 'pos': 0.125, 'compound': 0.835},
 141: {'neg': 0.098, 'neu': 0.787, 'pos': 0.114, 'compound': 0.2023},
 142: {'neg': 0.0, 'neu': 0.782, 'pos': 0.218, 'compound': 0.7814},
 143: {'neg': 0.0, 'neu': 0.763, 'pos': 0.237, 'compound': 0.9296},
 144: {'neg': 0.059, 'neu': 0.667, 'pos': 0.274, 'compound': 0.9653},
 145: {'neg': 0.058, 'neu': 0.841, 'pos': 0.102, 'compound': 0.6124},
 146: {'neg': 0.144, 'neu': 0.677, 'pos': 0.178, 'compound': 0.6341},
 147: {'neg': 0.087, 'neu': 0.783, 'pos': 0.13, 'compound': 0.7567},
 148: {'neg': 0.058, 'neu': 0.867, 'pos': 0.075, 'compound': 0.1533},
 149: {'neg': 0.04, 'neu': 0.833, 'pos': 0.127, 'compound': 0.6956},
 150: {'neg': 0.0, 'neu': 0.709, 'pos': 0.291, 'compound': 0.9231},
 151: {'neg': 0.0, 'neu': 0.564, 'pos': 0.436, 'compound': 0.9858},
 152: {'neg': 0.0, 'neu': 0.784, 'pos': 0.216, 'compound': 0.765},
 153: {'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'compound': 0.7269},
 154: {'neg': 0.12, 'neu': 0.76, 'pos': 0.12, 'compound': 0.2502},
 155: {'neg': 0.0, 'neu': 0.647, 'pos': 0.353, 'compound': 0.9803},
 156: {'neg': 0.0, 'neu': 0.768, 'pos': 0.232, 'compound': 0.9681},
 157: {'neg': 0.191, 'neu': 0.809, 'pos': 0.0, 'compound': -0.7269},
 158: {'neg': 0.071, 'neu': 0.514, 'pos': 0.415, 'compound': 0.8934},
 159: {'neg': 0.065, 'neu': 0.893, 'pos': 0.042, 'compound': -0.4721},
 160: {'neg': 0.081, 'neu': 0.779, 'pos': 0.14, 'compound': 0.4194},
 161: {'neg': 0.0, 'neu': 0.644, 'pos': 0.356, 'compound': 0.9117},
 162: {'neg': 0.106, 'neu': 0.894, 'pos': 0.0, 'compound': -0.5504},
 163: {'neg': 0.072, 'neu': 0.652, 'pos': 0.276, 'compound': 0.9517},
 164: {'neg': 0.047, 'neu': 0.869, 'pos': 0.085, 'compound': 0.4199},
 165: {'neg': 0.025, 'neu': 0.752, 'pos': 0.223, 'compound': 0.8957},
 166: {'neg': 0.032, 'neu': 0.717, 'pos': 0.251, 'compound': 0.9597},
 167: {'neg': 0.0, 'neu': 0.657, 'pos': 0.343, 'compound': 0.9098},
 168: {'neg': 0.05, 'neu': 0.905, 'pos': 0.045, 'compound': -0.1154},
 169: {'neg': 0.186, 'neu': 0.74, 'pos': 0.074, 'compound': -0.5283},
 170: {'neg': 0.141, 'neu': 0.832, 'pos': 0.028, 'compound': -0.7721},
 171: {'neg': 0.0, 'neu': 0.854, 'pos': 0.146, 'compound': 0.6476},
 172: {'neg': 0.04, 'neu': 0.844, 'pos': 0.116, 'compound': 0.6808},
 173: {'neg': 0.0, 'neu': 0.763, 'pos': 0.237, 'compound': 0.8906},
 174: {'neg': 0.022, 'neu': 0.788, 'pos': 0.189, 'compound': 0.9901},
 175: {'neg': 0.04, 'neu': 0.722, 'pos': 0.237, 'compound': 0.9782},
 176: {'neg': 0.0, 'neu': 0.874, 'pos': 0.126, 'compound': 0.7579},
 177: {'neg': 0.0, 'neu': 0.938, 'pos': 0.062, 'compound': 0.4215},
 178: {'neg': 0.058, 'neu': 0.794, 'pos': 0.148, 'compound': 0.6249},
 179: {'neg': 0.2, 'neu': 0.63, 'pos': 0.171, 'compound': 0.1203},
 180: {'neg': 0.048, 'neu': 0.829, 'pos': 0.122, 'compound': 0.7458},
 181: {'neg': 0.076, 'neu': 0.767, 'pos': 0.156, 'compound': 0.6085},
 182: {'neg': 0.0, 'neu': 0.433, 'pos': 0.567, 'compound': 0.9667},
 183: {'neg': 0.088, 'neu': 0.743, 'pos': 0.169, 'compound': 0.943},
 184: {'neg': 0.0, 'neu': 0.857, 'pos': 0.143, 'compound': 0.9577},
 185: {'neg': 0.11, 'neu': 0.593, 'pos': 0.297, 'compound': 0.6597},
 186: {'neg': 0.189, 'neu': 0.811, 'pos': 0.0, 'compound': -0.5994},
 187: {'neg': 0.016, 'neu': 0.842, 'pos': 0.142, 'compound': 0.9944},
 188: {'neg': 0.0, 'neu': 0.824, 'pos': 0.176, 'compound': 0.6983},
 189: {'neg': 0.0, 'neu': 0.843, 'pos': 0.157, 'compound': 0.8868},
 190: {'neg': 0.0, 'neu': 0.934, 'pos': 0.066, 'compound': 0.3506},
 191: {'neg': 0.148, 'neu': 0.64, 'pos': 0.212, 'compound': 0.4926},
 192: {'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.9062},
 193: {'neg': 0.055, 'neu': 0.728, 'pos': 0.217, 'compound': 0.8756},
 194: {'neg': 0.031, 'neu': 0.735, 'pos': 0.234, 'compound': 0.9595},
 195: {'neg': 0.082, 'neu': 0.483, 'pos': 0.435, 'compound': 0.8299},
 196: {'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'compound': 0.9538},
 197: {'neg': 0.0, 'neu': 0.917, 'pos': 0.083, 'compound': 0.4738},
 198: {'neg': 0.0, 'neu': 0.904, 'pos': 0.096, 'compound': 0.4153},
 199: {'neg': 0.0, 'neu': 0.701, 'pos': 0.299, 'compound': 0.8268},
 200: {'neg': 0.0, 'neu': 0.811, 'pos': 0.189, 'compound': 0.7178},
 201: {'neg': 0.039, 'neu': 0.888, 'pos': 0.072, 'compound': 0.6381},
 202: {'neg': 0.064, 'neu': 0.597, 'pos': 0.339, 'compound': 0.9531},
 203: {'neg': 0.0, 'neu': 0.688, 'pos': 0.312, 'compound': 0.8225},
 204: {'neg': 0.061, 'neu': 0.814, 'pos': 0.125, 'compound': 0.8728},
 205: {'neg': 0.0, 'neu': 0.882, 'pos': 0.118, 'compound': 0.6249},
 206: {'neg': 0.0, 'neu': 0.754, 'pos': 0.246, 'compound': 0.9368},
 207: {'neg': 0.0, 'neu': 0.59, 'pos': 0.41, 'compound': 0.8779},
 208: {'neg': 0.051, 'neu': 0.8, 'pos': 0.15, 'compound': 0.8436},
 209: {'neg': 0.05, 'neu': 0.82, 'pos': 0.13, 'compound': 0.8913},
 210: {'neg': 0.045, 'neu': 0.761, 'pos': 0.194, 'compound': 0.9893},
 211: {'neg': 0.075, 'neu': 0.755, 'pos': 0.171, 'compound': 0.9218},
 212: {'neg': 0.051, 'neu': 0.821, 'pos': 0.129, 'compound': 0.9529},
 213: {'neg': 0.051, 'neu': 0.838, 'pos': 0.11, 'compound': 0.4404},
 214: {'neg': 0.095, 'neu': 0.883, 'pos': 0.022, 'compound': -0.9726},
 215: {'neg': 0.0, 'neu': 0.891, 'pos': 0.109, 'compound': 0.6476},
 216: {'neg': 0.0, 'neu': 0.798, 'pos': 0.202, 'compound': 0.7964},
 217: {'neg': 0.078, 'neu': 0.922, 'pos': 0.0, 'compound': -0.296},
 218: {'neg': 0.015, 'neu': 0.884, 'pos': 0.101, 'compound': 0.9736},
 219: {'neg': 0.059, 'neu': 0.774, 'pos': 0.167, 'compound': 0.9424},
 220: {'neg': 0.031, 'neu': 0.702, 'pos': 0.267, 'compound': 0.9812},
 221: {'neg': 0.027, 'neu': 0.909, 'pos': 0.064, 'compound': 0.25},
 222: {'neg': 0.068, 'neu': 0.666, 'pos': 0.266, 'compound': 0.9883},
 223: {'neg': 0.0, 'neu': 0.779, 'pos': 0.221, 'compound': 0.9623},
 224: {'neg': 0.0, 'neu': 0.607, 'pos': 0.393, 'compound': 0.923},
 225: {'neg': 0.152, 'neu': 0.739, 'pos': 0.109, 'compound': -0.25},
 226: {'neg': 0.064, 'neu': 0.794, 'pos': 0.141, 'compound': 0.7951},
 227: {'neg': 0.139, 'neu': 0.754, 'pos': 0.108, 'compound': -0.3774},
 228: {'neg': 0.106, 'neu': 0.718, 'pos': 0.176, 'compound': 0.5475},
 229: {'neg': 0.0, 'neu': 0.837, 'pos': 0.163, 'compound': 0.6486},
 230: {'neg': 0.025, 'neu': 0.854, 'pos': 0.121, 'compound': 0.6478},
 231: {'neg': 0.03, 'neu': 0.726, 'pos': 0.244, 'compound': 0.9281},
 232: {'neg': 0.0, 'neu': 0.904, 'pos': 0.096, 'compound': 0.8144},
 233: {'neg': 0.0, 'neu': 0.807, 'pos': 0.193, 'compound': 0.8126},
 234: {'neg': 0.103, 'neu': 0.729, 'pos': 0.169, 'compound': 0.2481},
 235: {'neg': 0.0, 'neu': 0.805, 'pos': 0.195, 'compound': 0.8655},
 236: {'neg': 0.11, 'neu': 0.792, 'pos': 0.098, 'compound': -0.4786},
 237: {'neg': 0.041, 'neu': 0.793, 'pos': 0.166, 'compound': 0.9387},
 238: {'neg': 0.029, 'neu': 0.798, 'pos': 0.174, 'compound': 0.9936},
 239: {'neg': 0.064, 'neu': 0.7, 'pos': 0.236, 'compound': 0.9677},
 240: {'neg': 0.0, 'neu': 0.72, 'pos': 0.28, 'compound': 0.765},
 241: {'neg': 0.066, 'neu': 0.71, 'pos': 0.223, 'compound': 0.9553},
 242: {'neg': 0.0, 'neu': 0.765, 'pos': 0.235, 'compound': 0.807},
 243: {'neg': 0.0, 'neu': 0.76, 'pos': 0.24, 'compound': 0.9344},
 244: {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0},
 245: {'neg': 0.081, 'neu': 0.63, 'pos': 0.289, 'compound': 0.765},
 246: {'neg': 0.072, 'neu': 0.825, 'pos': 0.103, 'compound': 0.682},
 247: {'neg': 0.075, 'neu': 0.633, 'pos': 0.292, 'compound': 0.9757},
 248: {'neg': 0.0, 'neu': 0.869, 'pos': 0.131, 'compound': 0.7717},
 249: {'neg': 0.0, 'neu': 0.602, 'pos': 0.398, 'compound': 0.9351},
 250: {'neg': 0.0, 'neu': 0.75, 'pos': 0.25, 'compound': 0.7184},
 251: {'neg': 0.047, 'neu': 0.781, 'pos': 0.172, 'compound': 0.9476},
 252: {'neg': 0.076, 'neu': 0.924, 'pos': 0.0, 'compound': -0.4823},
 253: {'neg': 0.107, 'neu': 0.893, 'pos': 0.0, 'compound': -0.4767},
 254: {'neg': 0.0, 'neu': 0.801, 'pos': 0.199, 'compound': 0.9698},
 255: {'neg': 0.091, 'neu': 0.736, 'pos': 0.172, 'compound': 0.4118},
 256: {'neg': 0.103, 'neu': 0.699, 'pos': 0.198, 'compound': 0.9805},
 257: {'neg': 0.034, 'neu': 0.664, 'pos': 0.302, 'compound': 0.9463},
 258: {'neg': 0.105, 'neu': 0.816, 'pos': 0.079, 'compound': -0.3489},
 259: {'neg': 0.04, 'neu': 0.841, 'pos': 0.119, 'compound': 0.8883},
 260: {'neg': 0.0, 'neu': 0.833, 'pos': 0.167, 'compound': 0.8824},
 261: {'neg': 0.0, 'neu': 0.613, 'pos': 0.387, 'compound': 0.9493},
 262: {'neg': 0.0, 'neu': 0.54, 'pos': 0.46, 'compound': 0.9153},
 263: {'neg': 0.106, 'neu': 0.706, 'pos': 0.188, 'compound': 0.5849},
 264: {'neg': 0.098, 'neu': 0.875, 'pos': 0.026, 'compound': -0.9218},
 265: {'neg': 0.051, 'neu': 0.802, 'pos': 0.147, 'compound': 0.872},
 266: {'neg': 0.0, 'neu': 0.619, 'pos': 0.381, 'compound': 0.902},
 267: {'neg': 0.0, 'neu': 0.862, 'pos': 0.138, 'compound': 0.4926},
 268: {'neg': 0.062, 'neu': 0.911, 'pos': 0.028, 'compound': -0.7067},
 269: {'neg': 0.0, 'neu': 0.767, 'pos': 0.233, 'compound': 0.8176},
 270: {'neg': 0.032, 'neu': 0.794, 'pos': 0.174, 'compound': 0.9354},
 271: {'neg': 0.0, 'neu': 0.839, 'pos': 0.161, 'compound': 0.5927},
 272: {'neg': 0.062, 'neu': 0.863, 'pos': 0.074, 'compound': 0.2609},
 273: {'neg': 0.052, 'neu': 0.817, 'pos': 0.132, 'compound': 0.7003},
 274: {'neg': 0.0, 'neu': 0.733, 'pos': 0.267, 'compound': 0.7346},
 275: {'neg': 0.037, 'neu': 0.693, 'pos': 0.271, 'compound': 0.9421},
 276: {'neg': 0.132, 'neu': 0.711, 'pos': 0.157, 'compound': 0.3303},
 277: {'neg': 0.0, 'neu': 0.523, 'pos': 0.477, 'compound': 0.9542},
 278: {'neg': 0.025, 'neu': 0.809, 'pos': 0.167, 'compound': 0.937},
 279: {'neg': 0.072, 'neu': 0.641, 'pos': 0.288, 'compound': 0.8565},
 280: {'neg': 0.066, 'neu': 0.859, 'pos': 0.075, 'compound': 0.1666},
 281: {'neg': 0.049, 'neu': 0.823, 'pos': 0.127, 'compound': 0.6438},
 282: {'neg': 0.0, 'neu': 0.754, 'pos': 0.246, 'compound': 0.8016},
 283: {'neg': 0.028, 'neu': 0.934, 'pos': 0.038, 'compound': 0.1779},
 284: {'neg': 0.032, 'neu': 0.792, 'pos': 0.176, 'compound': 0.9852},
 285: {'neg': 0.0, 'neu': 0.864, 'pos': 0.136, 'compound': 0.5255},
 286: {'neg': 0.0, 'neu': 0.898, 'pos': 0.102, 'compound': 0.7917},
 287: {'neg': 0.0, 'neu': 0.857, 'pos': 0.143, 'compound': 0.919},
 288: {'neg': 0.035, 'neu': 0.801, 'pos': 0.163, 'compound': 0.9676},
 289: {'neg': 0.054, 'neu': 0.745, 'pos': 0.2, 'compound': 0.9557},
 290: {'neg': 0.039, 'neu': 0.697, 'pos': 0.264, 'compound': 0.8439},
 291: {'neg': 0.104, 'neu': 0.705, 'pos': 0.191, 'compound': 0.6257},
 292: {'neg': 0.052, 'neu': 0.745, 'pos': 0.203, 'compound': 0.9434},

In [12]:
vaders = pd.DataFrame(res).T # Convert the dictionary to a dataframe
vaders = vaders.reset_index().rename(columns={'index':'Id'}) # Reset the index and rename the column to 'Id'
vaders = vaders.merge(df, how='left') # Merge the dataframe with the original dataframe
# merged_df = pd.merge(df, vaders, on='Id', how='left') # Merge the dataframe with the original dataframe

In [13]:
# Showing the sentiment score with the metadata, only the first 5 rows
vaders.head()

,Id,neg,neu,pos,compound,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,0.000,0.695,0.305,0.9441,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,0.138,0.862,0.000,-0.5664,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,0.091,0.754,0.155,0.8265,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,0.000,1.000,0.000,0.0000,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,0.000,0.552,0.448,0.9468,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...